### ISSUE TITLE
All links are beginning with spaces

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#122] opened 2015-11-05 03:23 UTC
Minor priority, but this "problem" can have some cause on system.

![osmbc-spaces-in-links](https://cloud.githubusercontent.com/assets/957501/10959098/69e8a52c-8353-11e5-8474-89be46943deb.png)

**Comment by TheFive** [comment] 2015-11-05 08:32
Maybe just a JADE space is taken for display.

**Comment by fredao** [comment] 2015-11-05 12:51
it's not a bug, itś a feature.

**Comment by alexandre-mbm** [comment] 2015-11-05 17:41
@fredao, the space? Why?

**Comment by alexandre-mbm** [comment] 2015-11-05 18:03
@TheFive, perhaps it happened by manual deletion of previous link and it is not programming question.

**Comment by TheFive** [comment] 2015-11-05 18:58
May be it is a data problem. Was fixed by alexandre.

**Closed by TheFive** 2015-11-05 18:58 UTC
Labels: bug

**Comment by alexandre-mbm** [comment] 2015-11-05 21:52
I suggest the issue's label be changed from `bug` to `invalid`.
Anyway would be interesting make something like `s/^[ \t]*//` and `s/[ \t]*$//`.
