### ISSUE TITLE
Optimize loading of users SQL to improve performance

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#846] opened 2020-09-26 13:55 UTC
response: timeout exceeded when trying to connect

**Comment by TheFive** [comment] 2020-09-26 14:05
Trying to load the user list, results in timeout.
The problem is generated by counting all changes for each user, which results in a runtime problem in the current implementation.
As a workaround, there is only reloading the page 2 or 3 times, until all necessary data is successfully cached.

**Comment by TheFive** [comment] 2020-12-23 15:02
Temporarily fixed with new server. Still a better load of all users is needed (problem is counting article per user).

**Comment by TheFive** [comment] 2022-01-11 17:52
See
https://osmbc.openstreetmap.de/usert/list?access=full

**Comment by TheFive** [comment] 2022-06-17 15:40
should be a solved issue, after sevarel updates. Please feel free, to reopen if this occurs again

**Closed by TheFive** 2022-06-17 15:40 UTC
Labels: question
