### ISSUE TITLE
Comment is not opened the first time you write a comment.

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#177] opened 2015-11-22 01:11 UTC
In really, I was doing maintenance in ES markdown codes.

Examples:
- https://thefive.sabic.uberspace.de/changes/41605
- https://thefive.sabic.uberspace.de/changes/41593

---

![osmbc-comment-reopened](https://cloud.githubusercontent.com/assets/957501/11321397/d52c3fbe-909c-11e5-8b12-c7b9f1cada63.png)

**Comment by TheFive** [comment] 2015-11-22 08:09
I do not see the problem.

https://thefive.sabic.uberspace.de/article/10328, here so comment is set to open, as you have commented something.

Same here:
https://thefive.sabic.uberspace.de/article/10270

What went wrong ? Of course, if you enter a comment, the status has to be open, that the comment is shown in the blog view.

**Comment by alexandre-mbm** [comment] 2015-11-23 01:08
I had done comments at past. I think that it was solved already.

**Comment by TheFive** [comment] 2015-11-23 05:31
It works as intended. See my links.

**Comment by alexandre-mbm** [comment] 2015-11-23 06:02
I know that I had done comments there, but this was before.

**Comment by TheFive** [comment] 2015-11-23 06:30
Please show me that in the full article history and mark when you have written the comment and when the open status is set. Full screen dump, you know how to put nice red lines into a screen shot.
Please take the two article histories i have mentioned, as these two articles are marked as error from you.

**Comment by TheFive** [comment] 2015-11-23 06:31
You are right, the commentStatus is set "indirect" by saving an article the second time. This does not lead to any non working functions, as only the "open" and the "non existing" commentStatus does not make any difference in the OSMBC Behavior.

**Comment by alexandre-mbm** [comment] 2015-11-23 06:46
I think that the system should notify me and ask me if I am provoking reopening of the comment.

**Comment by TheFive** [comment] 2015-11-23 07:22
The system is still working as designed. Please show me in  history of the article where a status is set a way, that YOU did mot want.


Btw. You have POSTed the status via HTML, and it was YOUR decision to let the status OPEN. Of course you where able to close the comment at this stage.

Many people are working with comments and are happy, how they work. What is your problem, why do you burn developer time in discussing things, where the system did nothing wrong in implementation of user intention.
Is it just because you are discussing because of the discussion ?

I do not need this kind of support.


Christoph

**Comment by alexandre-mbm** [comment] 2015-11-23 09:17
I showed something. You is free to think it be irrelevant and then close this issue.

**Comment by TheFive** [comment] 2015-11-23 09:28
May be you have to be more concrete:

I think that the system (OSMBC) should notify me and ask me if I am causing reopening of the comment (comment in OSMBC).

But now it looks like you meant: GITHUB.

It confusing....

**Comment by alexandre-mbm** [comment] 2015-11-23 09:33
No, the your citation is correct:

> I think that the system (OSMBC) should notify me and ask me if I am causing reopening of the comment (comment in OSMBC).

But don't worry. I see importance in something that you don't see. **You is free for this.**

**Comment by TheFive** [comment] 2015-11-23 10:02
Yes, then show me please, where the status of the comment was set to a value, that you did not wanted.
Very easy question and no answer from your site yet.

And i would like to understand, where you need a notification form the system. For that i need what you did, and in which phase the missing notification was.

Not because something in the history is shown at the wrong place, but because the system is in a status that is wrong in the sense of user expectation of the status.


What you did is:

1) You collected something.
2) You edited a comment.
3) you edited a markdown.

Where is the need for an notification for a "REOPEN" now ?

**Comment by alexandre-mbm** [comment] 2015-11-23 18:51
Maybe I had not wanted say "notification", but a way of the user know that is causing `commenteStatus=open`, and a way to decide do not do this. In really, I don't remember if the comment had been "closed". If not, the `commenteStatus=open` came delayed. These steps 1, 2 and 3, I did in different moments, or at least the step 2 and the markdownES edit.

![osmbc-comment-reopen-with-es](https://cloud.githubusercontent.com/assets/957501/11346046/7858982e-91f9-11e5-9c41-8e725a8757d1.png)

Note: I was doing a small adjust in markdownES; my team is the PT.

If you think that is burning your time, take the matter as finished.

**Comment by TheFive** [comment] 2015-11-24 06:25
The osmbc assumption is, that a new comment is open, until it is closed manually.

That is a self explaining behaviour, all osmbc users are very happy with.

Why should the system write 

Be aware you have written a comment, to make this comment visible in the blog view i will open it ?


Sounds ridiculous.

**Comment by TheFive** [comment] 2015-11-24 07:47
To your screenshot:
See: https://github.com/TheFive/osmbc/issues/177#issuecomment-158861831 That explains the behavior total.

**Closed** 2015-12-05 19:06 UTC
Labels: bug
