### ISSUE TITLE
the markdown fields are not corresponding to the language settings

### ISSUE THREAD

**Issue by fredao** [TheFive/osmbc#332] opened 2016-02-15 08:48 UTC
![image](https://cloud.githubusercontent.com/assets/1868849/13043575/31005054-d3c9-11e5-9c8f-062781392ad6.png)

see: Language settings: EN - ES
and the markdown fields: DE - EN

**Comment by TheFive** [comment] 2016-02-20 11:06
Your screenshot is missing the URL.

**Comment by TheFive** [comment] 2016-02-20 11:07
The session settings displayed in the upper right corner can be overwritten by the url. 
That is for compaitibilby reasons during the change period, and that will be needed in future, to have external links to a given language for questions.

**Comment by TheFive** [comment] 2016-02-21 19:38
@fredao
Can you check, wether this was the link, that has overwritten the session data ?
Than it is not a bug, otherwise i need more information to re-enact the situation.

**Comment by TheFive** [comment] 2016-02-24 06:35
Unanswered callback. I close this issue.

**Closed by TheFive** 2016-02-24 06:35 UTC
Labels: question
